services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - BestNetwoks  # Указываем, что используем сеть BestNetwoks

networks:
  BestNetwoks:
    external: true  # Указываем, что сеть является внешней