# Используем образ Node.js в качестве базового
FROM node:22

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт 3000 для доступа к приложению
EXPOSE 3000

# Запускаем приложение
CMD ["npm", "start"]
