services:
  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: ..
      dockerfile: NotificationService/NotificationService.Api/Dockerfile
    ports:
      - "5040:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBUSER_NOTIFICATION=${ASPNETCORE_DBUSER_NOTIFICATION}
      - ASPNETCORE_DBPASSWORD_NOTIFICATION=${ASPNETCORE_DBPASSWORD_NOTIFICATION}
      - ASPNETCORE_DBBASE_NOTIFICATION=${ASPNETCORE_DBBASE_NOTIFICATION}
    depends_on:
      - notificationDb
  notificationrabbitconsumers:
    image: ${DOCKER_REGISTRY-}notificationrabbitconsumers
    build:
      context: ..
      dockerfile: NotificationService/NotificationService.RabbitConsumers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBUSER_NOTIFICATION=${ASPNETCORE_DBUSER_NOTIFICATION}
      - ASPNETCORE_DBPASSWORD_NOTIFICATION=${ASPNETCORE_DBPASSWORD_NOTIFICATION}
      - ASPNETCORE_DBBASE_NOTIFICATION=${ASPNETCORE_DBBASE_NOTIFICATION}
      - ASPNETCORE_RABIT_PORT=${ASPNETCORE_RABIT_PORT}
      - ASPNETCORE_RABIT_USER=${ASPNETCORE_RABIT_USER}
      - ASPNETCORE_RABIT_PASSWORD=${ASPNETCORE_RABIT_PASSWORD}
      - ASPNETCORE_RABIT_VHOST=${ASPNETCORE_RABIT_VHOST}
      - ASPNETCORE_RABIT_HOST=${ASPNETCORE_RABIT_HOST}
    depends_on:
      - notificationDb
  notificationDb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${ASPNETCORE_DBBASE_NOTIFICATION}
      POSTGRES_USER: ${ASPNETCORE_DBUSER_NOTIFICATION}
      POSTGRES_PASSWORD: ${ASPNETCORE_DBPASSWORD_NOTIFICATION}
    ports:
      - "5435:${ASPNETCORE_DBPORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default:
    name: "BestNetwoks"
