services:
  walletservice:
    image: ${DOCKER_REGISTRY-}walletservice
    build:
      context: ..
      dockerfile: WalletService/WalletService.Api/Dockerfile
    ports:
      - "5038:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBBASE=db_wallet
      - ASPNETCORE_RABIT_PORT=${ASPNETCORE_RABIT_PORT}
      - ASPNETCORE_RABIT_USER=${ASPNETCORE_RABIT_USER}
      - ASPNETCORE_RABIT_PASSWORD=${ASPNETCORE_RABIT_PASSWORD}
      - ASPNETCORE_RABIT_VHOST=${ASPNETCORE_RABIT_VHOST}
      - ASPNETCORE_RABIT_HOST=${ASPNETCORE_RABIT_HOST}
    depends_on:
      - mongoDbWallet
  mongoDbWallet:
    image: mongo:latest
    environment:
      MONGO_DB: db_wallet
    ports:
      - "27044:27017"
    volumes:
      - mongo_data:/var/lib/mongo/data
volumes:
  mongo_data:

networks:
  default:
    name: "BestNetwoks"
