services:
  betsService:
    image: ${DOCKER_REGISTRY-}betsservice
    build:
      context: ..
      dockerfile: BetsService/BetsService.Api/Dockerfile
    ports:
      - "5039:8080"
      - "7127:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBUSER=${ASPNETCORE_DBUSER_BETS}
      - ASPNETCORE_DBPASSWORD=${ASPNETCORE_DBPASSWORD_BETS}
      - ASPNETCORE_DBBASE=${ASPNETCORE_DBBASE_BETS}
      - ASPNETCORE_REDIS_PASSWORD=${ASPNETCORE_REDIS_PASSWORD}
      - ASPNETCORE_REDISPORT=${ASPNETCORE_REDIS_PORT}
    depends_on:
      - betsDb
  betsDb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${ASPNETCORE_DBBASE_BETS}
      POSTGRES_USER: ${ASPNETCORE_DBUSER_BETS}
      POSTGRES_PASSWORD: ${ASPNETCORE_DBPASSWORD_BETS}
    ports:
      - "5434:${ASPNETCORE_DBPORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default:
    name: "BestNetwoks"
