services:
  userserver:
    image: ${DOCKER_REGISTRY-}userserver
    build:
      context: ..
      dockerfile: UserService/UserServer/Dockerfile
    ports:
      - "5000:8080"
      #- "5035:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBUSER_USER_SERVICE=${ASPNETCORE_DBUSER_USER_SERVICE}
      - ASPNETCORE_DBPASSWORD_USER_SERVICE=${ASPNETCORE_DBPASSWORD_USER_SERVICE}
      - ASPNETCORE_DBBASE_USER_SERVICE=${ASPNETCORE_DBBASE_USER_SERVICE}
      - ASPNETCORE_REDIS_PASSWORD=${ASPNETCORE_REDIS_PASSWORD}
      - ASPNETCORE_REDIS_PORT=${ASPNETCORE_REDIS_PORT}
      - ASPNETCORE_RABIT_PORT=${ASPNETCORE_RABIT_PORT}
      - ASPNETCORE_RABIT_USER=${ASPNETCORE_RABIT_USER}
      - ASPNETCORE_RABIT_PASSWORD=${ASPNETCORE_RABIT_PASSWORD}
      - ASPNETCORE_RABIT_VHOST=${ASPNETCORE_RABIT_VHOST}
    depends_on:
      - postgresDBUsers
  postgresDBUsers:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${ASPNETCORE_DBBASE_USER_SERVICE}
      POSTGRES_USER: ${ASPNETCORE_DBUSER_USER_SERVICE}
      POSTGRES_PASSWORD: ${ASPNETCORE_DBPASSWORD_USER_SERVICE}
    ports:
      - "5432:${ASPNETCORE_DBPORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default:
    name: "BestNetwoks"
