name: Deploy to Production BetsSerciec

on:
  workflow_dispatch: # Ручной запуск через вкладку Actions
  workflow_run:
    workflows: ["Build and Test"] # Проверяет завершение первого workflow
    types:
      - completed
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    # Выполняется только если первый workflow завершился успешно
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add SSH key to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Stop existing containers
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /home/github/ci_test/project/BetsService/ && docker-compose stop"

      - name: Start docker-compose
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /home/github/ci_test/project/BetsService/ && docker-compose up -d --build"

      - name: Check container status
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker ps -a"
